# Generated by Django 5.0.6 on 2024-06-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstaMember",
            fields=[
                ("m_no", models.AutoField(primary_key=True, serialize=False)),
                ("m_id", models.CharField(max_length=300)),
                ("m_pwd", models.CharField(max_length=300)),
                ("m_salt", models.CharField(max_length=300)),
                ("m_name", models.CharField(max_length=100)),
                ("m_email", models.CharField(max_length=300)),
                ("m_img", models.CharField(blank=True, max_length=300, null=True)),
                ("m_active", models.BooleanField(default=True)),
                ("m_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "insta_member",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InstaMemberSingo",
            fields=[
                (
                    "ms_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="imanager.instamember",
                    ),
                ),
            ],
            options={
                "db_table": "insta_member_singo",
                "managed": False,
            },
        ),
    ]
